In [39]:
import pandas as pd
df=pd.read_csv('final_food_delivery_dataset.csv')
df.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name_x,name,city,membership,restaurant_name_y,cuisine,rating
0,1,2508,450,2023-02-18,842.97,New Foods Chinese,User_2508,Hyderabad,Regular,Restaurant_450,Mexican,3.2
1,2,2693,309,2023-01-18,546.68,Ruchi Curry House Multicuisine,User_2693,Pune,Regular,Restaurant_309,Indian,4.5
2,3,2084,107,2023-07-15,163.93,Spice Kitchen Punjabi,User_2084,Chennai,Gold,Restaurant_107,Mexican,4.0
3,4,319,224,2023-10-04,1155.97,Darbar Kitchen Non-Veg,User_319,Bangalore,Gold,Restaurant_224,Chinese,4.8
4,5,1064,293,2023-12-25,1321.91,Royal Eatery South Indian,User_1064,Pune,Regular,Restaurant_293,Italian,3.0

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           10000 non-null  int64
 1   user_id            10000 non-null  int64
 2   restaurant_id      10000 non-null  int64
 3   order_date         10000 non-null  object
 4   total_amount       10000 non-null  float64
 5   restaurant_name_x  10000 non-null  object
 6   name               10000 non-null  object
 7   city               10000 non-null  object
 8   membership         10000 non-null  object
 9   restaurant_name_y  10000 non-null  object
 10  cuisine            10000 non-null  object
 11  rating             10000 non-null  float64
dtypes: float64(2), int64(3), object(7)
memory usage: 937.6+ KB

In [41]:
df['membership'].value_counts()

membership
Regular    5013
Gold       4987
Name: count, dtype: int64

In [42]:
df.groupby('city')['total_amount'].sum()

city
Bangalore    2206946.58
Chennai      1990513.03
Hyderabad    1889366.58
Pune         1924797.93
Name: total_amount, dtype: float64

In [43]:
df.groupby('cuisine')['total_amount'].mean()

cuisine
Chinese    798.389020
Indian     798.466011
Italian    799.448578
Mexican    808.021344
Name: total_amount, dtype: float64

In [44]:
df['order_date']=pd.to_datetime(df['order_date'])
df['quarter']=df['order_date'].dt.to_period('Q')
df.groupby('quarter')['total_amount'].sum()

quarter
2023Q1    1993425.14
2023Q2    1945348.72
2023Q3    2037385.10
2023Q4    2018263.66
2024Q1      17201.50
Freq: Q-DEC, Name: total_amount, dtype: float64

In [45]:
df.shape, df.columns

((10000, 13),
 Index(['order_id', 'user_id', 'restaurant_id', 'order_date', 'total_amount',
        'restaurant_name_x', 'name', 'city', 'membership', 'restaurant_name_y',
        'cuisine', 'rating', 'quarter'],
       dtype='object'))

In [46]:
df[df['membership']=='Gold'].groupby('city')['total_amount'].sum().sort_values(ascending=False)

city
Chennai      1080909.79
Pune         1003012.32
Bangalore     994702.59
Hyderabad     896740.19
Name: total_amount, dtype: float64

In [47]:
df.groupby('cuisine')['total_amount'].mean().sort_values(ascending=False)

cuisine
Mexican    808.021344
Italian    799.448578
Indian     798.466011
Chinese    798.389020
Name: total_amount, dtype: float64

In [48]:
user_spend =df.groupby('user_id')['total_amount'].sum()
(user_spend > 1000).sum()

np.int64(2544)

In [49]:
def rating_bucket(r):
    if 3.0 <= r <= 3.5: return '3.0-3.5'
    if 3.6 <= r <= 4.0: return '3.6-4.0'
    if 4.1 <= r <= 4.5: return '4.1-4.5'
    return'4.6-5.0'
df['rating_range'] = df['rating'].apply(rating_bucket)

df.groupby('rating_range')['total_amount'].sum().sort_values(ascending=False)

rating_range
4.6-5.0    2197030.75
3.0-3.5    2136772.70
4.1-4.5    1960326.26
3.6-4.0    1717494.41
Name: total_amount, dtype: float64

In [50]:
df[df['membership']=='Gold'].groupby('city')['total_amount'].mean().sort_values(ascending=False)

city
Chennai      808.459080
Hyderabad    806.421034
Bangalore    793.223756
Pune         781.162243
Name: total_amount, dtype: float64

In [51]:
rev = df.groupby('cuisine')['total_amount'].sum()
count = df.groupby('cuisine')['restaurant_id'].nunique()

(rev / count).sort_values(ascending=False)

cuisine
Mexican    16292.992891
Chinese    16087.538750
Italian    16065.109524
Indian     15646.131587
dtype: float64

In [52]:
round((df[df['membership']=='Gold'].shape[0] / df.shape[0]) * 100)

50

In [53]:
restaurant_stats = df.groupby('restaurant_name_y').agg(
    orders=('order_id','count'),
    avg_order=('total_amount','mean')
)

restaurant_stats[restaurant_stats['orders'] < 20].sort_values('avg_order', ascending=False).head()

                   orders    avg_order
restaurant_name_y
Restaurant_294         13  1040.222308
Restaurant_262         18  1029.473333
Restaurant_77          12  1029.180833
Restaurant_193         15  1026.306667
Restaurant_7           16  1002.140625

In [54]:
df.groupby(['membership','cuisine'])['total_amount'].sum().sort_values(ascending=False)

membership  cuisine
Regular     Mexican    1072943.30
            Italian    1018424.75
Gold        Mexican    1012559.79
            Italian    1005779.05
Regular     Indian      992100.27
Gold        Indian      979312.31
            Chinese     977713.74
Regular     Chinese     952790.91
Name: total_amount, dtype: float64

In [55]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['quarter'] = df['order_date'].dt.to_period('Q')

df.groupby('quarter')['total_amount'].sum().sort_values(ascending=False)

quarter
2023Q3    2037385.10
2023Q4    2018263.66
2023Q1    1993425.14
2023Q2    1945348.72
2024Q1      17201.50
Freq: Q-DEC, Name: total_amount, dtype: float64

In [56]:
df[df['membership']=='Gold'].shape[0]

4987

In [57]:
round(df[df['city']=='Hyderabad']['total_amount'].sum())

1889367

In [58]:
df['user_id'].nunique()

2883

In [59]:
round(df[df['membership']=='Gold']['total_amount'].mean(), 2)

np.float64(797.15)

In [60]:
df[df['rating'] >= 4.5].shape[0]

3374

In [61]:
top_city = df[df['membership']=='Gold'].groupby('city')['total_amount'].sum().idxmax()

df[(df['membership']=='Gold') & (df['city']==top_city)].shape[0]

1337

In [62]:
print("orders ↔ users join key: user_id")
print("orders ↔ restaurants join key: restaurant_id")
print("Cuisine & rating source: restaurants.sql")
print("Membership source: users.json")
print("Pandas join function: merge()")
print("Food type column: cuisine")
print("Final dataset rows:", len(df))

orders ↔ users join key: user_id
orders ↔ restaurants join key: restaurant_id
Cuisine & rating source: restaurants.sql
Membership source: users.json
Pandas join function: merge()
Food type column: cuisine
Final dataset rows: 10000